/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AditorAIChat: typeof import('./src/components/aditor_extensions/aditorAIChat.vue')['default']
    AditorAudio: typeof import('./src/components/aditor_extensions/aditorAudio.vue')['default']
    AditorCanvas: typeof import('./src/components/aditor_extensions/aditorCanvas.vue')['default']
    AditorCode: typeof import('./src/components/aditor_extensions/aditorCode.vue')['default']
    AditorConfig: typeof import('./src/components/aditor_extensions/aditorConfig.vue')['default']
    AditorPDF: typeof import('./src/components/aditor_extensions/aditorPDF.vue')['default']
    AditorQuote: typeof import('./src/components/aditor_extensions/aditorQuote.vue')['default']
    AditorTitleParagraph: typeof import('./src/components/aditor_extensions/aditorTitleParagraph.vue')['default']
    AIAssistant: typeof import('./src/components/AIAssistant.vue')['default']
    Breadcrumb: typeof import('./src/components/Breadcrumb.vue')['default']
    Contextmenu: typeof import('./src/components/Contextmenu.vue')['default']
    Editor: typeof import('./src/components/Editor.vue')['default']
    EditorToolbarUpgrade: typeof import('./src/components/EditorToolbarUpgrade.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    Explorer: typeof import('./src/components/Explorer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Progress: typeof import('./src/components/Progress.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
