export const aiAssistantStates = [
    {
        "ID": 1,
        "inParagraphPosition": "start",
        "selectExtendName": "default",
        "around_sp_comonent": "default",
        "name1": "解释",
        "name2": "",
        "name3": "",
        "name4": "",
        "prompt1": "\"${before}{after}\"\n根据上面整篇文章，帮我解释\"${line}\"这一段内容",
        "prompt2": "",
        "prompt3": "",
        "prompt4": ""
    },
    {
        "ID": 2,
        "inParagraphPosition": "middle",
        "selectExtendName": "default",
        "around_sp_comonent": "default",
        "name1": "解释",
        "name2": "",
        "name3": "",
        "name4": "",
        "prompt1": "\"${before}{after}\"\n根据上面整篇文章，帮我解释\"${line}\"这一段内容",
        "prompt2": "",
        "prompt3": "",
        "prompt4": ""
    },
    {
        "ID": 3,
        "inParagraphPosition": "end",
        "selectExtendName": "default",
        "around_sp_comonent": "default",
        "name1": "补全",
        "name2": "翻译",
        "name3": "",
        "name4": "",
        "prompt1": "\"${before}{after}\"\n根据上面整篇文章，帮我补全\"${line}\"这一段后面的内容",
        "prompt2": "\"${before}{after}\"\n根据上面整篇文章，帮我翻译\"${line}\"这一段",
        "prompt3": "",
        "prompt4": ""
    },
    {
        "ID": 4,
        "inParagraphPosition": "start2middle",
        "selectExtendName": "default",
        "around_sp_comonent": "default",
        "name1": "解释",
        "name2": "翻译",
        "name3": "润色",
        "name4": "",
        "prompt1": "\"${before}${selected}${after}\"\n帮我解释这段内容中的\"${selected}\"部分",
        "prompt2": "\"${before}${selected}${after}\"\n帮我翻译这段内容中的\"${selected}\"部分",
        "prompt3": "\"${before}${selected}${after}\"\n帮我润色这段内容中的\"${selected}\"部分",
        "prompt4": ""
    },
    {
        "ID": 5,
        "inParagraphPosition": "middle2end",
        "selectExtendName": "default",
        "around_sp_comonent": "default",
        "name1": "解释",
        "name2": "翻译",
        "name3": "润色",
        "name4": "补全",
        "prompt1": "\"${before}${selected}${after}\"\n帮我解释这段内容中的\"${selected}\"部分",
        "prompt2": "\"${before}${selected}${after}\"\n帮我翻译这段内容中的\"${selected}\"部分",
        "prompt3": "\"${before}${selected}${after}\"\n帮我润色这段内容中的\"${selected}\"部分",
        "prompt4": "\"${before}${selected}${after}\"\n帮我补全这段内容中的\"${selected}\"部分后面的内容"
    },
    {
        "ID": 6,
        "inParagraphPosition": "start2end",
        "selectExtendName": "default",
        "around_sp_comonent": "default",
        "name1": "解释",
        "name2": "翻译",
        "name3": "润色",
        "name4": "补全",
        "prompt1": "\"${before}${selected}${after}\"\n帮我解释这段内容中的\"${selected}\"部分",
        "prompt2": "\"${before}${selected}${after}\"\n帮我翻译这段内容中的\"${selected}\"部分",
        "prompt3": "\"${before}${selected}${after}\"\n帮我润色这段内容中的\"${selected}\"部分",
        "prompt4": "\"${before}${selected}${after}\"\n帮我补全这段内容中的\"${selected}\"部分后面的内容"
    },
    {
        "ID": 7,
        "inParagraphPosition": "middle2middle",
        "selectExtendName": "default",
        "around_sp_comonent": "default",
        "name1": "解释",
        "name2": "翻译",
        "name3": "润色",
        "name4": "",
        "prompt1": "\"${before}${selected}${after}\"\n帮我解释这段内容中的\"${selected}\"部分",
        "prompt2": "\"${before}${selected}${after}\"\n帮我翻译这段内容中的\"${selected}\"部分",
        "prompt3": "\"${before}${selected}${after}\"\n帮我润色这段内容中的\"${selected}\"部分",
        "prompt4": ""
    },
    {
        "ID": 8,
        "inParagraphPosition": "start",
        "selectExtendName": "aditorKatex",
        "around_sp_comonent": "default",
        "name1": "解释公式",
        "name2": "",
        "name3": "",
        "name4": "",
        "prompt1": "\"${before}{after}\"\n\n根据上面整篇文章，帮我解释\"${line}\"这里的公式",
        "prompt2": "",
        "prompt3": "",
        "prompt4": ""
    },
    {
        "ID": 9,
        "inParagraphPosition": "middle",
        "selectExtendName": "aditorKatex",
        "around_sp_comonent": "default",
        "name1": "解释公式",
        "name2": "验证公式",
        "name3": "",
        "name4": "",
        "prompt1": "\"${before}{after}\"\n\n根据上面整篇文章，帮我解释\"${line}\"这里的公式",
        "prompt2": "\"${before}{after}\"\n\n根据上面整篇文章，帮我验证\"${line}\"这里的公式是否正确，合理",
        "prompt3": "",
        "prompt4": ""
    },
    {
        "ID": 10,
        "inParagraphPosition": "end",
        "selectExtendName": "aditorKatex",
        "around_sp_comonent": "default",
        "name1": "补全公式",
        "name2": "联想公式",
        "name3": "解释公式",
        "name4": "",
        "prompt1": "\"${before}{after}\"\n\n根据上面整篇文章，帮我补全\"${line}\"这里的公式",
        "prompt2": "\"${before}{after}\"\n\n根据上面整篇文章，帮我联想是否有和\"${line}\"这里的公式等价的变形，或者替换形式",
        "prompt3": "\"${before}{after}\"\n\n根据上面整篇文章，帮我解释\"${line}\"这里的公式",
        "prompt4": ""
    },
    {
        "ID": 11,
        "inParagraphPosition": "start2middle",
        "selectExtendName": "aditorKatex",
        "around_sp_comonent": "default",
        "name1": "解释公式",
        "name2": "验证公式",
        "name3": "联想公式",
        "name4": "",
        "prompt1": "\"${before}${selected}${after}\"\n根据上面整篇文章，帮我解释这段内容中的\"${selected}\"公式",
        "prompt2": "\"${before}${selected}${after}\"\n根据上面整篇文章，帮我验证这段内容中的\"${selected}\"公式",
        "prompt3": "\"${before}${selected}${after}\"\n根据上面整篇文章，帮我联想是否有公式\"${selected}\"等价的变形，或者替换形式",
        "prompt4": ""
    },
    {
        "ID": 12,
        "inParagraphPosition": "middle2end",
        "selectExtendName": "aditorKatex",
        "around_sp_comonent": "default",
        "name1": "解释公式",
        "name2": "验证公式",
        "name3": "补全公式",
        "name4": "联想公式",
        "prompt1": "\"${before}${selected}${after}\"\n根据上面整篇文章，帮我解释这段内容中的\"${selected}\"公式",
        "prompt2": "\"${before}${selected}${after}\"\n根据上面整篇文章，帮我验证这段内容中的\"${selected}\"公式",
        "prompt3": "\"${before}${selected}${after}\"\n根据上面整篇文章，帮我补全这段内容中的\"${selected}\"公式",
        "prompt4": "\"${before}${selected}${after}\"\n根据上面整篇文章，帮我联想是否有公式\"${selected}\"等价的变形，或者替换形式"
    },
    {
        "ID": 13,
        "inParagraphPosition": "start2end",
        "selectExtendName": "aditorKatex",
        "around_sp_comonent": "default",
        "name1": "解释公式",
        "name2": "验证公式",
        "name3": "补全公式",
        "name4": "联想公式",
        "prompt1": "\"${before}${selected}${after}\"\n根据上面整篇文章，帮我解释这段内容中的\"${selected}\"公式",
        "prompt2": "\"${before}${selected}${after}\"\n根据上面整篇文章，帮我验证这段内容中的\"${selected}\"公式",
        "prompt3": "\"${before}${selected}${after}\"\n根据上面整篇文章，帮我补全这段内容中的\"${selected}\"公式",
        "prompt4": "\"${before}${selected}${after}\"\n根据上面整篇文章，帮我联想是否有公式\"${selected}\"等价的变形，或者替换形式"
    },
    {
        "ID": 14,
        "inParagraphPosition": "middle2middle",
        "selectExtendName": "aditorKatex",
        "around_sp_comonent": "default",
        "name1": "解释公式",
        "name2": "验证公式",
        "name3": "联想公式",
        "name4": "",
        "prompt1": "\"${before}${selected}${after}\"\n根据上面整篇文章，帮我解释这段内容中的\"${selected}\"公式",
        "prompt2": "\"${before}${selected}${after}\"\n根据上面整篇文章，帮我验证这段内容中的\"${selected}\"公式",
        "prompt3": "\"${before}${selected}${after}\"\n根据上面整篇文章，帮我联想是否有公式\"${selected}\"等价的变形，或者替换形式",
        "prompt4": ""
    },
    {
        "ID": 15,
        "inParagraphPosition": "start",
        "selectExtendName": "aditorCode",
        "around_sp_comonent": "default",
        "name1": "解释代码",
        "name2": "",
        "name3": "",
        "name4": "",
        "prompt1": "\"${before}${selected}${after}\"\n根据上面整篇文章，帮我解释这段内容中的\"${line}\"代码",
        "prompt2": "",
        "prompt3": "",
        "prompt4": ""
    },
    {
        "ID": 16,
        "inParagraphPosition": "middle",
        "selectExtendName": "aditorCode",
        "around_sp_comonent": "default",
        "name1": "解释代码",
        "name2": "补全代码",
        "name3": "代码注释",
        "name4": "",
        "prompt1": "\"${before}${selected}${after}\"\n根据上面整篇文章，帮我解释这段内容中的\"${line}\"代码",
        "prompt2": "\"${before}${selected}${after}\"\n根据上面整篇文章，帮我补全这段内容中的\"${line}\"代码",
        "prompt3": "\"${before}${selected}${after}\"\n根据上面整篇文章，帮我给这段内容中的\"${line}\"加上注释",
        "prompt4": ""
    },
    {
        "ID": 17,
        "inParagraphPosition": "end",
        "selectExtendName": "aditorCode",
        "around_sp_comonent": "default",
        "name1": "补全代码",
        "name2": "解释代码",
        "name3": "代码注释",
        "name4": "",
        "prompt1": "\"${before}${selected}${after}\"\n根据上面整篇文章，帮我补全这段内容中的\"${line}\"代码",
        "prompt2": "\"${before}${selected}${after}\"\n根据上面整篇文章，帮我解释这段内容中的\"${line}\"代码",
        "prompt3": "",
        "prompt4": ""
    },
    {
        "ID": 18,
        "inParagraphPosition": "start2middle",
        "selectExtendName": "aditorCode",
        "around_sp_comonent": "default",
        "name1": "解释代码",
        "name2": "优化代码",
        "name3": "验证代码",
        "name4": "",
        "prompt1": "\"${before}${selected}${after}\"\n根据上面整篇文章，帮我解释这段内容中的\"${selected}\"代码",
        "prompt2": "\"${before}${selected}${after}\"\n根据上面整篇文章，帮我优化这段内容中的\"${selected}\"代码",
        "prompt3": "\"${before}${selected}${after}\"\n根据上面整篇文章，帮我验证这段内容中的\"${selected}\"代码是否有问题",
        "prompt4": ""
    },
    {
        "ID": 19,
        "inParagraphPosition": "middle2end",
        "selectExtendName": "aditorCode",
        "around_sp_comonent": "default",
        "name1": "解释代码",
        "name2": "优化代码",
        "name3": "验证代码",
        "name4": "补全代码",
        "prompt1": "\"${before}${selected}${after}\"\n帮我解释这段内容中的\"${selected}\"代码",
        "prompt2": "\"${before}${selected}${after}\"\n帮我优化这段内容中的\"${selected}\"代码",
        "prompt3": "\"${before}${selected}${after}\"\n帮我验证这段内容中的\"${selected}\"代码是否有问题",
        "prompt4": "\"${before}${selected}${after}\"\n帮我补全这段内容中的\"${selected}\"部分代码"
    },
    {
        "ID": 20,
        "inParagraphPosition": "start2end",
        "selectExtendName": "aditorCode",
        "around_sp_comonent": "default",
        "name1": "解释代码",
        "name2": "优化代码",
        "name3": "验证代码",
        "name4": "补全代码",
        "prompt1": "\"${before}${selected}${after}\"\n根据上面整篇文章，帮我解释这段内容中的\"${selected}\"代码",
        "prompt2": "\"${before}${selected}${after}\"\n根据上面整篇文章，帮我优化这段内容中的\"${selected}\"代码",
        "prompt3": "\"${before}${selected}${after}\"\n根据上面整篇文章，帮我验证这段内容中的\"${selected}\"代码是否有问题",
        "prompt4": "\"${before}${selected}${after}\"\n根据上面整篇文章，帮我补全这段内容中的\"${selected}\"部分代码"
    },
    {
        "ID": 21,
        "inParagraphPosition": "middle2middle",
        "selectExtendName": "aditorCode",
        "around_sp_comonent": "default",
        "name1": "解释代码",
        "name2": "优化代码",
        "name3": "验证代码",
        "name4": "",
        "prompt1": "\"${before}${selected}${after}\"\n根据上面整篇文章，帮我解释这段内容中的\"${selected}\"代码",
        "prompt2": "\"${before}${selected}${after}\"\n根据上面整篇文章，帮我优化这段内容中的\"${selected}\"代码",
        "prompt3": "\"${before}${selected}${after}\"\n根据上面整篇文章，帮我验证这段内容中的\"${selected}\"代码是否有问题",
        "prompt4": ""
    },
    {
        "ID": 22,
        "inParagraphPosition": "start",
        "selectExtendName": "aditorCanvas",
        "around_sp_comonent": "default",
        "name1": "联想提示词",
        "name2": "",
        "name3": "",
        "name4": "",
        "prompt1": "\"${before}${selected}${after}\"\n根据上下文的内容，给我一些符合描述的AI绘画提示词，以英文短句和词组出现，逗号分割",
        "prompt2": "",
        "prompt3": "",
        "prompt4": ""
    },
    {
        "ID": 23,
        "inParagraphPosition": "middle",
        "selectExtendName": "aditorCanvas",
        "around_sp_comonent": "default",
        "name1": "联想提示词",
        "name2": "",
        "name3": "",
        "name4": "",
        "prompt1": "\"${before}${selected}${after}\"\n根据上下文的内容，给我一些符合描述的AI绘画提示词，以英文短句和词组出现，逗号分割",
        "prompt2": "",
        "prompt3": "",
        "prompt4": ""
    },
    {
        "ID": 24,
        "inParagraphPosition": "end",
        "selectExtendName": "aditorCanvas",
        "around_sp_comonent": "default",
        "name1": "联想提示词",
        "name2": "",
        "name3": "",
        "name4": "",
        "prompt1": "\"${before}${selected}${after}\"\n根据上下文的内容，给我一些符合描述的AI绘画提示词，以英文短句和词组出现，逗号分割",
        "prompt2": "",
        "prompt3": "",
        "prompt4": ""
    },
    {
        "ID": 25,
        "inParagraphPosition": "start2middle",
        "selectExtendName": "aditorCanvas",
        "around_sp_comonent": "default",
        "name1": "转英文",
        "name2": "转中文",
        "name3": "优化提示词",
        "name4": "联想提示词",
        "prompt1": "帮我把\"${selected}\"这段AI绘画的中文Prompt翻译为英文",
        "prompt2": "帮我把\"${selected}\"这段AI绘画的英文Prompt翻译为中文",
        "prompt3": "\"${before}${selected}${after}\"\n根据上下文的内容，帮我优化\"${selected}\"部分的AI绘画Prompt",
        "prompt4": "\"${before}${selected}${after}\"\n根据上下文的内容，帮我联想和\"${selected}\"部分相关的AI绘画Prompt"
    },
    {
        "ID": 26,
        "inParagraphPosition": "middle2end",
        "selectExtendName": "aditorCanvas",
        "around_sp_comonent": "default",
        "name1": "转英文",
        "name2": "转中文",
        "name3": "优化提示词",
        "name4": "联想提示词",
        "prompt1": "帮我把\"${selected}\"这段AI绘画的中文Prompt翻译为英文",
        "prompt2": "帮我把\"${selected}\"这段AI绘画的英文Prompt翻译为中文",
        "prompt3": "\"${before}${selected}${after}\"\n根据上下文的内容，帮我优化\"${selected}\"部分的AI绘画Prompt",
        "prompt4": "\"${before}${selected}${after}\"\n根据上下文的内容，帮我联想和\"${selected}\"部分相关的AI绘画Prompt"
    },
    {
        "ID": 27,
        "inParagraphPosition": "start2end",
        "selectExtendName": "aditorCanvas",
        "around_sp_comonent": "default",
        "name1": "转英文",
        "name2": "转中文",
        "name3": "优化提示词",
        "name4": "联想提示词",
        "prompt1": "帮我把\"${selected}\"这段AI绘画的中文Prompt翻译为英文",
        "prompt2": "帮我把\"${selected}\"这段AI绘画的英文Prompt翻译为中文",
        "prompt3": "\"${before}${selected}${after}\"\n根据上下文的内容，帮我优化\"${selected}\"部分的AI绘画Prompt",
        "prompt4": "\"${before}${selected}${after}\"\n根据上下文的内容，帮我联想和\"${selected}\"部分相关的AI绘画Prompt"
    },
    {
        "ID": 28,
        "inParagraphPosition": "middle2middle",
        "selectExtendName": "aditorCanvas",
        "around_sp_comonent": "default",
        "name1": "转英文",
        "name2": "转中文",
        "name3": "优化提示词",
        "name4": "联想提示词",
        "prompt1": "帮我把\"${selected}\"这段AI绘画的中文Prompt翻译为英文",
        "prompt2": "帮我把\"${selected}\"这段AI绘画的英文Prompt翻译为中文",
        "prompt3": "\"${before}${selected}${after}\"\n根据上下文的内容，帮我优化\"${selected}\"部分的AI绘画Prompt",
        "prompt4": "\"${before}${selected}${after}\"\n根据上下文的内容，帮我联想和\"${selected}\"部分相关的AI绘画Prompt"
    }
]